In [1]:
import numpy as np
import pandas as pd 
from keras.utils import to_categorical
from keras import Sequential 
from keras.layers import Dense
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'keras'

In [50]:
data = np.load('Downloads/dev.npy', allow_pickle = True, encoding = 'bytes')
labels = np.load('Downloads/dev_labels.npy', allow_pickle = True, encoding = 'bytes')

In [51]:
data.shape, labels.shape

((1103,), (1103,))

In [52]:
data[0].shape, data[1].shape, data[2].shape

((388, 40), (416, 40), (467, 40))

### Flatenning and converting labels into one hot encoding

In [53]:
data_processed = np.vstack(data)
sum = data_processed.shape[0]
data_processed[0]

array([-2.7760592e+00, -1.0653754e+01, -9.3995695e+00, -1.0137558e-02,
       -8.1852531e+00, -2.0760990e+01, -1.5297649e+01, -2.9380997e+01,
       -3.7393414e+01, -2.6283970e+01, -4.2670517e+01, -2.2047264e+01,
       -1.7182083e+01, -1.5833426e+00, -2.8240342e+00, -4.5740137e+00,
       -2.9991994e+00, -2.1732755e+00, -2.7392473e+00, -1.0618892e+00,
       -1.5344710e+00, -6.8763638e-01, -2.6726961e+00, -1.6712704e+00,
       -1.4890862e+00, -8.1220293e-01, -5.7070589e-01, -8.2221556e-01,
       -9.7150373e-01, -3.0292416e-01, -4.8017311e-01, -7.1806431e-01,
       -1.0571270e+00, -1.5789652e-01, -8.7490082e-02, -2.3755646e-01,
        1.3585186e-01,  2.3635530e-01, -5.8059311e-01, -8.1715870e-01],
      dtype=float32)

In [54]:
stack_arr_label = np.full([1,1], None)

for i in range(labels.shape[0]):
    stack_arr_label = np.vstack((stack_arr_label, labels[i].reshape(-1,1)))
stack_arr_label = stack_arr_label[1:sum + 1]
stack_arr_label.shape

(669294, 1)

In [55]:
final_label = []

for label in stack_arr_label:
    final_label.append(label[0])

final_label = np.array(final_label) 
final_label.shape

(669294,)

In [56]:
x_train, x_test, y_train, y_test = train_test_split(data_processed, final_label, test_size=0.3, random_state=42)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((468505, 40), (200789, 40), (468505, 138), (200789, 138))

In [57]:
x_train[0], y_train[0]

(array([-9.7317219e-02,  1.1685652e+01,  3.0461803e+01,  3.6332504e+01,
         4.1506119e+00,  9.1195297e+00,  2.6136833e+01,  7.9378647e+01,
         9.1363655e+01,  4.8359482e+01,  4.4012459e+01,  1.1751607e+02,
         1.0804644e+02,  3.8047371e+00,  6.5696163e+00,  6.0983763e+00,
         3.1477575e+00,  6.8607359e+00,  5.8980284e+00,  7.5497236e+00,
         7.1485291e+00,  3.8774080e+00,  2.3407221e+00,  2.4847889e+00,
         3.0401297e+00,  3.7598581e+00,  4.2438822e+00,  5.3463898e+00,
         6.4585590e+00,  6.0444851e+00,  4.9826880e+00,  4.5033064e+00,
         5.2820215e+00,  4.3367510e+00,  2.9441347e+00,  2.6579990e+00,
         2.6135836e+00,  2.6680956e+00,  2.0346422e+00,  2.7619867e+00],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 

## Model Building

In [58]:
model = Sequential([
    Dense(512, input_dim = 40, activation="relu"),
    Dense(1024,activation="relu"),
    Dense(138,activation="softmax")
])

model.compile(optimizer = "adam",
              loss = "categorical_crossentropy",
              metrics = ["accuracy"])

model.fit(x_train,y_train,batch_size=100,epochs=10)

Epoch 1/10
4686/4686 [==============================] - 223s 43ms/step - loss: 3.0691 - accuracy: 0.2383
Epoch 2/10
4686/4686 [==============================] - 167s 36ms/step - loss: 2.8631 - accuracy: 0.2708
Epoch 3/10
4686/4686 [==============================] - 165s 35ms/step - loss: 2.7972 - accuracy: 0.2826
Epoch 4/10
4686/4686 [==============================] - 155s 33ms/step - loss: 2.7586 - accuracy: 0.2899
Epoch 5/10
4686/4686 [==============================] - 136s 29ms/step - loss: 2.7300 - accuracy: 0.2948
Epoch 6/10
4686/4686 [==============================] - 136s 29ms/step - loss: 2.7107 - accuracy: 0.2988
Epoch 7/10
4686/4686 [==============================] - 141s 30ms/step - loss: 2.6958 - accuracy: 0.3020
Epoch 8/10
4686/4686 [==============================] - 137s 29ms/step - loss: 2.6823 - accuracy: 0.3043
Epoch 9/10
4686/4686 [==============================] - 165s 35ms/step - loss: 2.6713 - accuracy: 0.3069
Epoch 10/10
4686/4686 [==============================] 

In [48]:
model = Sequential()
model.add(Dense(512, input_dim=40, activation='relu')) 
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu')) 
model.add(Dense(138, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
4686/4686 [==============================] - 295s 62ms/step - loss: 3.0370 - accuracy: 0.2400
Epoch 2/100
4686/4686 [==============================] - 269s 57ms/step - loss: 2.8240 - accuracy: 0.2760
Epoch 3/100
4686/4686 [==============================] - 239s 51ms/step - loss: 2.7523 - accuracy: 0.2892
Epoch 4/100
3129/4686 [===================>..........] - ETA: 1:18 - loss: 2.7041 - accuracy: 0.2978

KeyboardInterrupt: 

In [ ]:
model.save('speech_model')

In [ ]:
model.evaluate(x_test, y_test)